config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
    get 'signup', to: 'users#new'
    post 'users', to: 'users#create'
    resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
    belongs_to :user
    validates :title, presence: true, length: {minimum:3, maximum:20}
    validates :description, presence: true, length: {minimum:5, maximum:25}
end

app/models/user.rb
class User < ApplicationRecord 
    before_save {self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, length: {minimum:3, maximum:25}, uniqueness: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:125}, uniqueness: { case_sensitive: false }, format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    def show
    end

    def index 
        @articles= Article.all
    end

    def new 
        @article= Article.new
    end

    def edit 
    end

    def create 
        @article= Article.new(article_params)
        @article.user= User.first
        @article.save
         if @article.save
            flash[:notice] = "article was created successfully"
        redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def update 

        if @article.update(article_params)
            flash[:notice]="updated successfullu"
            redirect_to article_path
            else 
                render 'edit'
        end

    end

    def destroy 
        @article.destroy 
        redirect_to articles_path
    end


    private 
    def set_article 
        @article = Article.find(params[:id])
    end

    def article_params 
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show 
        @user= User.find(params[:id])
    end

    def index 
        @users= User.all
    end
  def new
    @user = User.new
  end

  def edit 
    @user= User.find(params[:id])
  end

  def update 
    @user=User.find(params[:id])
    if @user.update(user_params) 
        flash[:notice]="user is updated successfuly"
        redirect_to articles_path
    else
       render edit
    end

  end

  def create 
    @user= User.new(user_params)
    if @user.save 
        flash[:notice]="welcome to alpha blog #{ @user.username}"
        redirect_to articles_path
    else 
        render 'new'
    end

  end

  private

  def user_params 
    params.require(:user).permit(:username,:email,:password)
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%=form_with model: @article, local: true do |f|%>
<p><%=f.label :title%>
<%=f.text_field :title%>
</p>
<p>
<%= f.label :description%>
<%= f.text_area :description%>
</p>
<%= f.submit%>
<%end%>

app/views/articles/edit.html.erb
<h1> Editing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Index page</h1>
<table> 
<thead>
<tr>
<th>Title</th>
<th>Description</th>
<th>Action</th>
</tr>
</thead>

<tbody>
<% @articles.each do |article|%>

<tr>
<td><%= article.title%></td>
<td><%= article.description%>   --><%=article.user.username if article.user%></td>
<td><%=link_to 'Delete' , article_path(article), method: :delete %></td>
<td><%=link_to 'edit' , edit_article_path(article) %></td>
<td><%=link_to 'show' , article_path(article) %></td>
</tr>
<%end%>
</tbody>
</table>

app/views/articles/new.html.erb
<h1>create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Show data</h1>

<h3>Title:     <%=@article.title%><br/></h3>
<h3>desscription:  <%=@article.description%></h3>

<h4>by   <%= @article.user.username if @article.user%></h4>

app/views/layouts/_messages.html.erb
   <%flash.each do |name, message|%>
    <%=message%>
   
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%=form_with model: @user, local: true do |f|%>
<p><%=f.label :username%>
<%=f.text_field :username%>
</p>
<p>
<%= f.label :email%>
<%= f.email_field :email%>
</p>
<p>
<%= f.label :password%>
<%= f.password_field :password%>
</p>
<%= f.submit (@user.new_record? ? "sign up" : "update account")%>
<%end%>

app/views/users/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>List of users</h1>

<% @users.each do |user|%>
<%= user.articles.inspect%>
<%end%>

app/views/users/new.html.erb
<h1>signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Showing users</h1>

<p><%= @user.username%></p>
<p><%= @user.email%><p>